#!/usr/bin/env bash

export BOILERPLATE_NO_COLOR="true"

source "${BASH_SOURCE[0]%/*}/../lib/bash/core.sh"

function main() {

  # Update submodules
  (
    set -x
    git submodule update --init --recursive
  )

  # Remove untracked submodules
  (
    set -x
    git ls-files "${PWD}" --exclude-standard --others |
      while IFS='' read -r UNTRACKED; do
        if [[ -f "${UNTRACKED}/.git" ]]; then
          (
            set -x
            rm -rf "${UNTRACKED}"
          )
        fi
      done
  )

}

main "$@"
