#!/usr/bin/env bash

export BOILERPLATE_NO_COLOR="true"

# shellcheck disable=SC1090
source "${BASH_SOURCE[0]%/*}/../lib/bash/core.sh"

function main() {

  (
    set -x
    git submodule update --init --recursive
  )

}

main "$@"
