#!/usr/bin/env bash

export BOILERPLATE_NO_COLOR="true"

source "${BASH_SOURCE[0]%/*}/../lib/bash/core.sh"

function main() {

  "${BASH_SOURCE[0]%/*}/../pipeline/build"

  (
    set -x
    git add "./build/"*
  )

  "${BASH_SOURCE[0]%/*}/../pipeline/lint-staged"

}

main "$@"
