#!/usr/bin/env bash

export BOILERPLATE_NO_COLOR="true"

source "${BASH_SOURCE[0]%/*}/../lib/bash/core.sh"

function main() {

  # Git LFS
  command -v git-lfs >/dev/null 2>&1 || {
    print >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-commit.\n"
    exit 2
  }
  git lfs pre-push "$@"

}

main "$@"
