#!/usr/bin/env bash

export BOILERPLATE_NO_COLOR="true"

source "./lib/bash/core.sh"

function main() {

  "./pipeline/build"

  (
    set -x
    git add "./build/"*
  )

  "./pipeline/lint-staged"

}

main "$@"
