ARG NODE_VERSION="lts"

FROM node:${NODE_VERSION}-alpine

WORKDIR /app

RUN \
  apk add \
  --virtual "shared-dependencies" \
  "bash" \
  "ca-certificates" \
  "jq"

ENTRYPOINT [ \
  "./pipeline/debug" \
  ]
