ARG VERSION="latest"

FROM alpine:${VERSION}

WORKDIR /app

RUN \
  apk add \
  --virtual "shared-dependencies" \
  "bash" \
  "jq"

RUN curl -s "https://raw.githubusercontent.com/envkey/envkey-source/master/install.sh" | bash

ENTRYPOINT [ \
  "./pipeline/debug" \
  ]
