ARG NODE_VERSION="lts"

FROM node:${NODE_VERSION}-alpine

WORKDIR /app

RUN \
  apk add \
  --virtual "shared-dependencies" \
  "bash" \
  "ca-certificates" \
  "curl" \
  "jq"

RUN curl -s "https://raw.githubusercontent.com/envkey/envkey-source/master/install.sh" | bash

ENTRYPOINT [ \
  "./pipeline/debug" \
  ]
