#!/usr/bin/env bash

# shellcheck disable=SC1090
source "${BASH_SOURCE[0]%/*}/../lib/bash/core.sh"

function replace() {

  local OLD_TEXT="${1:-}"
  local NEW_TEXT="${2:-}"

  grep -E --recursive "${OLD_TEXT}" . |
    grep '^\./' |
    grep --invert-match '^\./\.git/\|^\./pipeline/boilerplate-init' |
    awk '{print $1}' |
    sed 's|:.*$||' |
    uniq |
    while IFS='' read -r FILE; do
      sed -i.bak "s|${OLD_TEXT}|${NEW_TEXT}|g" "${FILE}"
      rm "${FILE}.bak"
    done
}

function main() {

  echo -e "${OK_COLOR}==> Initializing boilerplate..."

  "${BASH_SOURCE[0]%/*}/boilerplate-upgrade"

  echo "Project name (ex. \"My Project\"): "
  (
    local PROJECT_NAME
    read -r PROJECT_NAME
    replace "My Project" "${PROJECT_NAME}"
  )

  echo "Project key (ex. \"myproject\"): "
  (
    local PROJECT_KEY
    read -r PROJECT_KEY
    replace "myproject" "${PROJECT_KEY}"
  )

}

main "$@"
