#!/usr/bin/env bash

source "./lib/bash/core.sh"

function main() {

  echo -e "${OK_COLOR}==> Initializing boilerplate..."

  "./pipeline/boilerplate-upgrade"

  (
    set -x
    git add --all
    git commit --message "Setup project"
  )

}

main "$@"
