#!/usr/bin/env bash

# shellcheck disable=SC1090
source "${BASH_SOURCE[0]%/*}/../lib/bash/core.sh"

function main() {

  echo -e "${OK_COLOR}==> Upgrading boilerplate..."

  # "z" to keep remote at the bottom
  # to prevent auto-push
  REMOTE_NAME="zboilerplate"

  (
    set -x
    git fetch \
      --tags \
      --prune \
      "${REMOTE_NAME}"
  )

  CONFIG_FILE="./.boilerplate/config.json"
  if [[ -f "${CONFIG_FILE}" ]]; then
    BRANCH="$(jq --raw-output ".branch" "${CONFIG_FILE}")"
  fi

  if [[ -z "${BRANCH:-}" || "${BRANCH:-}" == "null" ]]; then

    echo "Which of these boilerplate branches do you want to upgrade to?"
    git branch --remotes | grep "${REMOTE_NAME}" | sed "s|.*${REMOTE_NAME}/|- |"

    read -r BRANCH

    NEW_CONFIG="$(jq --raw-output ".branch = \"${BRANCH}\"" "${CONFIG_FILE}")"
    echo "${NEW_CONFIG}" >"${CONFIG_FILE}"
  fi

  (
    set -x
    git merge \
      --allow-unrelated-histories \
      "${REMOTE_NAME}/${BRANCH}"
  )

}

main "$@" ||
  catch "$?" &&
  finally
