#!/usr/bin/env bash

# shellcheck disable=SC1090
source "${BASH_SOURCE[0]%/*}/lib/core.sh"

function main() {

  echo -e "${OK_COLOR}==> Cleaning...${NO_COLOR}"

  (
    set -x
    rm -rf "./node_modules"
    rm -rf "./build"
  )
}

main "$@" ||
  catch "$?" &&
  finally
