#!/usr/bin/env bash

# shellcheck disable=SC1090
source "${BASH_SOURCE[0]%/*}/../lib/bash/core.sh"

function main() {

  echo -e "${OK_COLOR}==> Cleaning...${NO_COLOR}"

}

main "$@" ||
  catch "$?" &&
  finally
