#!/usr/bin/env bash

# shellcheck disable=SC1090
source "${BASH_SOURCE[0]%/*}/../lib/bash/core.sh"

# shellcheck disable=SC1090
source "${BASH_SOURCE[0]%/*}/../lib/bash/node.sh"

function main() {

  if [[ ! -d "./node_modules" ]]; then
    "${BASH_SOURCE[0]%/*}/install"
  fi

  echo -e "${OK_COLOR}==> Debugging app..."

  NPM="$(command -v npm)"

  (
    set -x
    "${NPM}" run dev
  )

}

main "$@" ||
  catch "$?" &&
  finally
