#!/usr/bin/env bash

# shellcheck disable=SC1090
source "${BASH_SOURCE[0]%/*}/../lib/bash/core.sh"

function main() {

  echo -e "${OK_COLOR}==> Debugging app..."

  if [[ -z "${ENVKEY:-}" && -f "./.env" ]]; then
    while IFS='' read -r LINE; do
      export "${LINE?}"
    done <"./.env"
  fi

}

main "$@"
