#!/usr/bin/env bash

# shellcheck disable=SC1090
source "${BASH_SOURCE[0]%/*}/../lib/bash/core.sh"

function main() {

  echo -e "${OK_COLOR}==> Delivering app..."

  (
    set -x
    "${BASH_SOURCE[0]%/*}/../terraform/apply-ecr"
    "${BASH_SOURCE[0]%/*}/../lib/bash/aws-ecr-pull"
    "${BASH_SOURCE[0]%/*}/docker-build"
    "${BASH_SOURCE[0]%/*}/../lib/bash/aws-ecr-push"
  )
}

main "$@"
