#!/usr/bin/env bash

# shellcheck disable=SC1090
source "${BASH_SOURCE[0]%/*}/../lib/bash/core.sh"

function main() {

  echo -e "${OK_COLOR}==> Delivering app..."

  "${BASH_SOURCE[0]%/*}/docker-build"
}

main "$@" ||
  catch "$?" &&
  finally
