#!/usr/bin/env bash

# shellcheck source=./lib/bash/core.sh
source "${BASH_SOURCE[0]%/*}/../lib/bash/core.sh"

function main() {

  echo -e "${OK_COLOR}==> Deploying app..."

  loadDeployEnvKey --

  echo "${GIT_COMMIT}" >"./public/git-commit"

  if [[ -z "${GIT_BRANCH:-}" ]]; then
    GIT_BRANCH="$(git branch --show-current)"
    export GIT_BRANCH="${GIT_BRANCH}"
  fi

  loadEnvKey --optional

}

main "$@"
