#!/usr/bin/env bash

source "${BASH_SOURCE[0]%/*}/../lib/bash/core.sh"

function main() {

  echo -e "${OK_COLOR}==> Deploying app..."

  # "${BASH_SOURCE[0]%/*}/../terraform/apply"
  "${BASH_SOURCE[0]%/*}/../lib/bash/aws-ecs-update-services"

}

main "$@"
