#!/usr/bin/env bash

source "${BASH_SOURCE[0]%/*}/../lib/bash/core.sh"

function main() {

  echo -e "${OK_COLOR}==> Building Docker image..."

  local DOCKER_COMPOSE_FILE="./docker-compose.yml"

  PROJECT_KEY="$(projectKey)"
  export PROJECT_KEY="${PROJECT_KEY}"

  GIT_COMMIT_HASH="$(git rev-parse --short HEAD)"
  export GIT_COMMIT_HASH="${GIT_COMMIT_HASH}"

  NODE_VERSION="$(head -n 1 ./.node-version)"
  export NODE_VERSION="${NODE_VERSION}"

  if [[ ! -f "./.env" ]]; then
    touch "./.env"
  fi

  # SSH
  if [[ -f "${HOME}/.ssh/id_rsa" ]]; then
    rm -rf "./.ssh"
    mkdir "./.ssh"
    cp "${HOME}/.ssh/id_rsa" "./.ssh/id_rsa"
  fi

  (
    set -x
    docker-compose \
      --file "${DOCKER_COMPOSE_FILE}" \
      build \
      --parallel
  )

}

main "$@"
