#!/usr/bin/env bash

# shellcheck disable=SC1090
source "$(dirname "${BASH_SOURCE[0]}")/lib/core.sh"

function main() {

  DOCKER_COMPOSE_FILE="./docker-compose.debug.yml"

  NODE_VERSION="$(head -n 1 "./.nvmrc")"

  (
    set -x
    docker-compose \
      --file "${DOCKER_COMPOSE_FILE}" \
      build \
      --build-arg "NODE_VERSION=${NODE_VERSION}"
  )

  (
    set -x
    docker-compose \
      --file "${DOCKER_COMPOSE_FILE}" \
      up
  )

}

main "$@" ||
  catch "$?" &&
  finally
