#!/usr/bin/env bash

# shellcheck disable=SC1090
source "${BASH_SOURCE[0]%/*}/../lib/bash/core.sh"

function main() {

  DOCKER_COMPOSE_FILE="./docker-compose.yml"

  (
    set -x
    docker-compose \
      --file "${DOCKER_COMPOSE_FILE}" \
      build
  )

}

main "$@" ||
  catch "$?" &&
  finally
