#!/usr/bin/env bash

# shellcheck disable=SC1090
source "${BASH_SOURCE[0]%/*}/lib/core.sh"

function main() {

  DOCKER_COMPOSE_FILE="./docker-compose.debug.yml"

  NODE_VERSION="$(jq --raw-output ".devDependencies.node" "./package.json")"

  (
    set -x
    docker-compose \
      --file "${DOCKER_COMPOSE_FILE}" \
      build \
      --build-arg "NODE_VERSION=${NODE_VERSION}"
  )

  (
    set -x
    docker-compose \
      --file "${DOCKER_COMPOSE_FILE}" \
      up
  )

}

main "$@" ||
  catch "$?" &&
  finally
