#!/usr/bin/env bash

# shellcheck disable=SC1090
source "${BASH_SOURCE[0]%/*}/../lib/bash/core.sh"

function main() {

  echo -e "${OK_COLOR}==> Debugging app in Docker..."

  local DOCKER_COMPOSE_FILE="./docker-compose.debug.yml"

  PROJECT_KEY="$(projectKey)"
  export PROJECT_KEY="${PROJECT_KEY}"

  GIT_COMMIT_HASH="$(git rev-parse --short HEAD)"
  export GIT_COMMIT_HASH="${GIT_COMMIT_HASH}"

  NODE_VERSION="$(head -n 1 ./.node-version)"
  export NODE_VERSION="${NODE_VERSION}"

  local VENDOR_FOLDER="./node_modules/node-sass/vendor"
  if [[ -d "${VENDOR_FOLDER}" ]]; then

    local ARCHITECTURE
    ARCHITECTURE="$(
      find "${VENDOR_FOLDER}" -depth 1 |
        head -n 1 |
        sed \
          -e 's|\./.*/||' \
          -e 's|-.*||'
    )"

    local EXPECTED_ARCHITECTURE="linux_musl"

    if [[ "${ARCHITECTURE}" != "${EXPECTED_ARCHITECTURE}" ]]; then
      echo "\"node_modules\" architecture is \"${ARCHITECTURE}\". Expect \"${EXPECTED_ARCHITECTURE}\"."
      (
        set -x
        "${BASH_SOURCE[0]%/*}/clean"
      )
    fi

  fi

  (
    set -x
    docker-compose \
      --file "${DOCKER_COMPOSE_FILE}" \
      build \
      --parallel
  )

  (
    set -x
    docker-compose \
      --file "${DOCKER_COMPOSE_FILE}" \
      up
  )

}

main "$@"
