#!/usr/bin/env bash

# shellcheck disable=SC1090
source "${BASH_SOURCE[0]%/*}/../lib/bash/core.sh"

function main() {

  echo -e "${OK_COLOR}==> Running built Docker image..."

  local DOCKER_COMPOSE_FILE="./docker-compose.yml"

  PROJECT_KEY="$(jq --raw-output '.name' "./package.json")"
  export PROJECT_KEY="${PROJECT_KEY}"

  GIT_COMMIT_HASH="$(git rev-parse --short HEAD)"
  export GIT_COMMIT_HASH="${GIT_COMMIT_HASH}"

  NODE_VERSION="$(head -n 1 ./.nvmrc)"
  export NODE_VERSION="${NODE_VERSION}"

  (
    set -x
    docker-compose \
      --file "${DOCKER_COMPOSE_FILE}" \
      up
  )

}

main "$@"
