#!/usr/bin/env bash

# shellcheck disable=SC1090
source "${BASH_SOURCE[0]%/*}/lib/core.sh"

function main() {

  FILE="${1}"

  if [[ -d "./node_modules" ]]; then
    PATH="${PWD}/node_modules/.bin:${PATH}"
  fi

  (
    set -x
    tsm "${FILE}"
  )

  HEADER_FILE="${FILE}.d.ts"

  if [[ -f "${HEADER_FILE}" ]]; then

    (
      set -x

      prettier \
        --write \
        "${HEADER_FILE}"

      eslint \
        --fix \
        --no-ignore \
        "${HEADER_FILE}"
    )

  fi

}

main "$@" ||
  catch "$?" &&
  finally
