#!/usr/bin/env bash

# shellcheck disable=SC1090
source "${BASH_SOURCE[0]%/*}/lib/core.sh"

function main() {

  FILE="${1}"
  FILE_NAME="${FILE##*/}"
  TEMP_FILE="./pipeline/${FILE_NAME}.css"

  cp -a "${FILE}" "${TEMP_FILE}"

  (
    set -x

    ./node_modules/.bin/tcm \
      "./pipeline"

    ./node_modules/.bin/prettier \
      --write \
      "${TEMP_FILE}.d.ts"

    ./node_modules/.bin/eslint \
      --fix \
      --no-ignore \
      "${TEMP_FILE}.d.ts"
  )

  cp -a "${TEMP_FILE}.d.ts" "${FILE}.d.ts"

  rm -rf "${TEMP_FILE}"*
}

main "$@" ||
  catch "$?" &&
  finally
