#!/usr/bin/env bash

# shellcheck source=./lib/bash/core.sh
source "${BASH_SOURCE[0]%/*}/../lib/bash/core.sh"

# shellcheck source=./lib/bash/templates.sh
source "${BASH_SOURCE[0]%/*}/../lib/bash/templates.sh"

# shellcheck source=./lib/bash/node.sh
source "${BASH_SOURCE[0]%/*}/../lib/bash/node.sh"

function main() {

  local PRODUCTION="false"
  if [[ "$*" == *"--production"* ]]; then
    PRODUCTION="true"
  fi

  if [[ "${HOME:-}" == "/vercel" ]]; then
    (
      set -x
      rm -rf "./node_modules"
      rm -rf "./submodules/"*"/node_modules"
    )
  fi

  echo -e "${OK_COLOR}==> Installing dependencies..."

  applyEnvVarsToTemplateFiles || removeGeneratedFiles

  # Fix git+ssh "unsupported option accept-new"
  # See https://github.com/npm/git/issues/31#issuecomment-862267072
  export GIT_SSH_COMMAND="ssh"

  if [[ -n "${BITBUCKET_USERNAME:-}" && -n "${BITBUCKET_PASSWORD:-}" ]]; then
    echo "Setting up Git for BitBucket..."
    (
      # set -x
      git config --global url."https://${BITBUCKET_USERNAME}:${BITBUCKET_PASSWORD}@bitbucket.org/".insteadOf "ssh://git@bitbucket.org/" || true
      git config --global url."https://${BITBUCKET_USERNAME}:${BITBUCKET_PASSWORD}@bitbucket.org/".insteadOf "git@bitbucket.org:" || true
      git config --global url."https://${BITBUCKET_USERNAME}:${BITBUCKET_PASSWORD}@bitbucket.org/".insteadOf "https://bitbucket.org/" || true
    )
  fi

  (
    set -x
    rm -rf "./package-lock.json"
    rm -rf "./yarn.lock"
    rm -rf "./pnpm-lock.yaml"
    npm install --location=global "npm@latest" || true # Latest npm may not support current Node.js version
    npm install --location=global "corepack@latest"
    corepack enable
    corepack prepare pnpm@latest --activate
  )

  if [[ -z "$*" ]]; then
    (
      set -x
      pnpm install ||
        pnpm install
    )
  else
    (
      set -x
      pnpm add "$@"
    )
  fi

  (
    set -x
    pnpm run "postinstall"
  )

  if [[ "${PRODUCTION}" != "true" ]]; then
    (
      set -x
      pnpm audit || true
    )
    sleep 1
  fi

}

main "$@"
