#!/usr/bin/env bash

# shellcheck source=./lib/bash/core.sh
source "${BASH_SOURCE[0]%/*}/../lib/bash/core.sh"

# shellcheck source=./lib/bash/node.sh
source "${BASH_SOURCE[0]%/*}/../lib/bash/node.sh"

function main() {

  local PRODUCTION="false"
  if [[ "$*" == *"--production"* ]]; then
    PRODUCTION="true"
  fi

  if [[ "${HOME:-}" == "/vercel" ]]; then
    (
      set -x
      rm -rf "./node_modules"
      rm -rf "./submodules/"*"/node_modules"
    )
  fi

  echo -e "${OK_COLOR}==> Installing dependencies..."

  # Fix git+ssh "unsupported option accept-new"
  # See https://github.com/npm/git/issues/31#issuecomment-862267072
  export GIT_SSH_COMMAND="ssh"

  if [[ -n "${BITBUCKET_USERNAME:-}" && -n "${BITBUCKET_PASSWORD:-}" ]]; then
    echo "Setting up Git for BitBucket..."
    (
      # set -x
      git config --global url."https://${BITBUCKET_USERNAME}:${BITBUCKET_PASSWORD}@bitbucket.org/".insteadOf "ssh://git@bitbucket.org/"
      git config --global url."https://${BITBUCKET_USERNAME}:${BITBUCKET_PASSWORD}@bitbucket.org/".insteadOf "git@bitbucket.org:"
      git config --global url."https://${BITBUCKET_USERNAME}:${BITBUCKET_PASSWORD}@bitbucket.org/".insteadOf "https://bitbucket.org/"
    )
  fi

  NPX="$(command -v npx)"
  NPM_VERSION="7.24.1"

  (
    set -x
    # "--force" accepts dependency conflict
    "${NPX}" "npm@${NPM_VERSION}" install \
      --force \
      "$@" ||
      "${NPX}" "npm@${NPM_VERSION}" install \
        --force \
        "$@"
  )

  if [[ "${PRODUCTION}" != "true" ]]; then
    (
      set -x
      "${NPX}" "npm@${NPM_VERSION}" audit || true
    )
  fi

}

main "$@"
