#!/usr/bin/env bash

source "./lib/bash/core.sh"
source "./lib/bash/node.sh"

function main() {

  echo -e "${OK_COLOR}==> Installing dependencies..."

  NPM="$(command -v npm)"

  (
    set -x
    "${NPM}" install \
      "$@"
  )

}

main "$@"
