#!/usr/bin/env bash

# shellcheck disable=SC1090
source "${BASH_SOURCE[0]%/*}/../lib/bash/core.sh"

dependency "shellcheck"

# shellcheck disable=SC1090
source "${BASH_SOURCE[0]%/*}/../lib/bash/node.sh"

function main() {

  if [[ ! -d "./node_modules" ]]; then
    "${BASH_SOURCE[0]%/*}/install"
  fi

  echo -e "${OK_COLOR}==> Linting code..."

  (
    set -x
    shellcheck "./lib/bash/"* "./pipeline/"*
  )

  NPM="$(command -v npm)"

  (
    set -x
    "${NPM}" run lint
  )

}

main "$@"
