#!/usr/bin/env bash

# shellcheck disable=SC1090
source "${BASH_SOURCE[0]%/*}/lib/core.sh"

# shellcheck disable=SC1090
source "${BASH_SOURCE[0]%/*}/lib/node.sh"

function main() {

  echo -e "${OK_COLOR}==> Linting code..."

  (
    set -x
    npm run lint
  )

}

main "$@" ||
  catch "$?" &&
  finally
