#!/usr/bin/env bash

# shellcheck source=./lib/bash/core.sh
source "${BASH_SOURCE[0]%/*}/../lib/bash/core.sh"

# shellcheck source=./lib/bash/templates.sh
source "${BASH_SOURCE[0]%/*}/../lib/bash/templates.sh"

dependency "shellcheck"

function main() {

  echo -e "${OK_COLOR}==> Linting code..."

  applyEnvVarsToTemplateFiles || removeGeneratedFiles

  (
    set -x
    shellcheck \
      --external-sources \
      "./.bin/"* \
      "./lib/bash/"* \
      "./pipeline/"* ||
      shellcheck \
        "./.bin/"* \
        "./lib/bash/"* \
        "./pipeline/"*
  )

}

main "$@"
