#!/usr/bin/env bash

export BOILERPLATE_LOG_TIME=true
export BOILERPLATE_NO_COLOR=true

source "${BASH_SOURCE[0]%/*}/../lib/bash/core.sh"

source "${BASH_SOURCE[0]%/*}/../lib/bash/node.sh"

function main() {

  echo -e "${OK_COLOR}==> Running app..."

  loadEnvKey

  NPM="$(command -v npm)"

  (
    set -x
    "${NPM}" start
  )

}

main "$@"
