#!/usr/bin/env bash

# shellcheck disable=SC1090
source "$(dirname "${BASH_SOURCE[0]}")/lib/core.sh"

function main() {

  echo -e "${OK_COLOR}==> Running app..."

  (
    set -x
    npm start
  )

}

prefix "$@"
main "$@"
suffix "$@"
