#!/usr/bin/env bash

# shellcheck disable=SC1090
source "${BASH_SOURCE[0]%/*}/lib/core.sh"

function main() {

  echo -e "${OK_COLOR}==> Running app..."

  checkNodeVersion

  (
    set -x
    npm start
  )

}

main "$@" ||
  catch "$?" &&
  finally
