#!/usr/bin/env bash

# shellcheck disable=SC1090
source "$(dirname "${BASH_SOURCE[0]}")/lib/core.sh"

function main() {

  DOCKER_COMPOSE_FILE="./docker-compose.yml"

  (
    set -x
    docker-compose \
      --file "${DOCKER_COMPOSE_FILE}" \
      build
  )

  (
    set -x
    docker-compose \
      --file "${DOCKER_COMPOSE_FILE}" \
      up
  )

}

prefix "$@"
main "$@"
suffix "$@"
