#!/usr/bin/env bash

# shellcheck source=./lib/bash/core.sh
source "${BASH_SOURCE[0]%/*}/../lib/bash/core.sh"

function main() {

  echo -e "${OK_COLOR}==> Setting up project..."

  # EnvKey
  echo
  echo "Setting up runtime EnvKeys..."

  read -p "EnvKey for branch 'develop': " -r ENVKEY_DEVELOP
  printf "\n# Develop\n# ENVKEY=%s\n" "${ENVKEY_DEVELOP}" >>"./.env"

  read -p "EnvKey for branch 'master': " -r ENVKEY_MASTER
  printf "\n# Master\n# ENVKEY=%s\n" "${ENVKEY_MASTER}" >>"./.env"

}

main "$@"
