#!/usr/bin/env bash

# shellcheck disable=SC1090
source "${BASH_SOURCE[0]%/*}/lib/core.sh"

# shellcheck disable=SC1090
source "${BASH_SOURCE[0]%/*}/lib/node.sh"

function main() {

  echo -e "${OK_COLOR}==> Testing app..."

  (
    set -x
    npm run coverage
  )

}

main "$@" ||
  catch "$?" &&
  finally
