#!/usr/bin/env bash

source "./lib/bash/core.sh"
source "./lib/bash/node.sh"

function main() {

  if [[ ! -d "./node_modules" ]]; then
    "./pipeline/install"
  fi

  echo -e "${OK_COLOR}==> Testing app..."

  loadEnvKey

  NPM="$(command -v npm)"

  (
    set -x
    "${NPM}" run coverage
  )

}

main "$@"
