#!/usr/bin/env bash

# shellcheck disable=SC1090
source "${BASH_SOURCE[0]%/*}/../lib/bash/core.sh"

function main() {

  echo -e "${OK_COLOR}==> Testing app..."

  if [[ -z "${ENVKEY:-}" && -f "./.env" ]]; then
    while IFS='' read -r LINE; do
      if [[ "${LINE}" == *"="* && "${LINE}" != "#"* ]]; then
        export "${LINE?}"
      fi
    done <"./.env"
  fi

  if [[ -n "${ENVKEY:-}" ]]; then
    dependency "envkey-source"
    eval "$(envkey-source "${ENVKEY}")"
  fi

}

main "$@"
