#!/usr/bin/env bash

source "${BASH_SOURCE[0]%/*}/../lib/bash/core.sh"

source "${BASH_SOURCE[0]%/*}/../lib/bash/node.sh"

function kill-server() {
  # shellcheck disable=SC2009
  ps -ef |
    grep "node" |
    grep "react-scripts" |
    awk '{print $2}' |
    xargs kill
}

function main() {

  echo
  echo "Killing the server from last run..."
  kill-server || true

  PROJECT_DIR="${PWD}"

  cd "./example" || return 1

  NPM="$(command -v npm)"

  (
    set -x
    "${NPM}" install
  )

  # Import envkey for test
  cp "./src/App.js" "./src/App.js.bak"

  printenv |
    grep -E '[A-Z_]+=' |
    grep --invert-match -E '[A-Z_]+_COLOR=' |
    while IFS="" read -r PAIR; do
      local KEY="${PAIR%%=*}"
      local VALUE="${PAIR#*=}"
      (
        # set -x
        sed -i.temp "s|process\\.env\\.${KEY}|\"${VALUE}\"|" "./src/App.js"
      )
    done

  rm "./src/App.js.temp"

  (
    set -x
    "${NPM}" start
  ) &

  cd "${PROJECT_DIR}" || return 1

  NPX="$(command -v npx)"

  (
    set -x
    "${NPX}" wait-on "http://localhost:3000"
  )

  (
    set -x
    "${NPX}" cypress run
  )

  echo
  echo "Killing the server..."
  kill-server

  sleep 1s

  if [[ -f "./example/src/App.js.bak" ]]; then
    mv "./example/src/App.js.bak" "./example/src/App.js"
  fi

}

main "$@"
