#!/usr/bin/env bash

source "${BASH_SOURCE[0]%/*}/core"

function main() {

  cd "${BASH_SOURCE[0]%/*}" || exit

  terraform init

  terraform plan \
    -var-file="./variables.tfvars" \
    -out="${PLAN_FILE}" \
    -state="${STATE_FILE}"

  # if ! (terraform show "${PLAN_FILE}" | grep "This plan does nothing."); then

  #   terraform show "${PLAN_FILE}"
  #   # terraform apply "${PLAN_FILE}"

  # fi

  # git add "${STATE_FILE}"
  # git commit -m ""
  # git push

  # terraform apply -var-file="./variables.tfvars" -state="${STATE_FILE}" -auto-approve

}

main "$@"
