#!/usr/bin/env bash

# shellcheck disable=SC1090
source "${BASH_SOURCE[0]%/*}/core"

function main() {

  NAMESPACE_ID="$(
    aws servicediscovery list-namespaces |
      jq -r ".Namespaces[] | select(.Name == \"${AWS_NAMESPACE}\") | .Id"
  )"

  sed -i "" -e "s|__AWS_ACCESS_KEY_ID__|${AWS_ACCESS_KEY_ID}|g" "${BASH_SOURCE[0]%/*}/variables.tfvars"
  sed -i "" -e "s|__AWS_SECRET_ACCESS_KEY__|${AWS_SECRET_ACCESS_KEY}|g" "${BASH_SOURCE[0]%/*}/variables.tfvars"
  sed -i "" -e "s|__NAME__|${NAME}|g" "${BASH_SOURCE[0]%/*}/variables.tfvars"
  sed -i "" -e "s|__SUBNET_NAME__|${AWS_SUBNET}|g" "${BASH_SOURCE[0]%/*}/variables.tfvars"
  sed -i "" -e "s|__LOAD_BALANCER_NAME__|${AWS_LOAD_BALANCER}|g" "${BASH_SOURCE[0]%/*}/variables.tfvars"
  sed -i "" -e "s|__NAMESPACE_ID__|${NAMESPACE_ID}|g" "${BASH_SOURCE[0]%/*}/variables.tfvars"
  sed -i "" -e "s|__SERVICE_ENVKEY__|${SERVICE_ENVKEY}|g" "${BASH_SOURCE[0]%/*}/variables.tfvars"
  sed -i "" -e "s|__IMAGE_TAG__|$(git rev-parse --short HEAD)|g" "${BASH_SOURCE[0]%/*}/variables.tfvars"

  cd "${BASH_SOURCE[0]%/*}" || exit

  terraform init

  (
    set -x
    terraform plan \
      -var-file="./variables.tfvars" \
      -out="${PLAN_FILE}" \
      -target="module.${NAME}.aws_ecr_repository.ecr_repo"
  )
}

main "$@"
