#!/usr/bin/env bash

# shellcheck disable=SC1090
source "${BASH_SOURCE[0]%/*}/core"

function main() {

  cd "${BASH_SOURCE[0]%/*}" || exit

  terraform init

  # terraform plan \
  #   -var-file="./variables.tfvars" \
  #   -out="${PLAN_FILE}" \
  #   -state="${STATE_FILE}" \
  #   -target="module.${NAME}.aws_ecr_repository.ecr_repo" \
  #   -target="module.${NAME}.aws_ecs_cluster.ecs_cluster" \
  #   -target="module.${NAME}.aws_autoscaling_group.autoscaling_group" \
  #   -target="module.${NAME}.aws_launch_configuration.launch_configuration" \
  #   -target="module.${NAME}.aws_security_group.security_group"

  # if ! (terraform show "${PLAN_FILE}" | grep "This plan does nothing."); then

  #   terraform show "${PLAN_FILE}"
  #   # terraform apply "${PLAN_FILE}"

  # fi

  # git add "${STATE_FILE}"
  # git commit -m ""
  # git push

  # terraform apply -var-file="./variables.tfvars" -state="${STATE_FILE}" -auto-approve

}

main "$@"
