#!/usr/bin/env bash

source "${BASH_SOURCE[0]%/*}/../lib/bash/core.sh"

dependency "aws"
dependency "envkey-source"

export PLAN_FILE="./terraform.tfplan"
export CONFIG_FILE="./terraform.config.json"
export VARIABLES_FILE="./variables.tfvars"
export STATE_FILE="./terraform.tfstate"

function update_json_file() {

  local FILTER="${1:-}"
  local FILEPATH="${2:-}"

  local TEMP_FILE
  TEMP_FILE="$(mktemp)"
  cat \
    <<<"$(jq -r "${FILTER}" "${FILEPATH}")" \
    >"${TEMP_FILE}" &&
    mv "${TEMP_FILE}" "${FILEPATH}"
}

function main() {

  if [[ -z "${DEPLOY_ENVKEY:-}" && -f "./.env" ]]; then
    while IFS='' read -r LINE; do
      if [[ "${LINE}" == *"="* && "${LINE}" != "#"* ]]; then
        export "${LINE?}"
      fi
    done <"./.env"
  fi

  if [[ -z "${DEPLOY_ENVKEY:-}" ]]; then
    echo "ERROR: Missing DEPLOY_ENVKEY." >&2
    exit 1
  fi

  eval "$(envkey-source "${DEPLOY_ENVKEY}")"

  if [[ -z "${AWS_DEFAULT_REGION:-}" ]]; then
    local AWS_DEFAULT_REGION="us-east-1"
    export AWS_DEFAULT_REGION="${AWS_DEFAULT_REGION}"
  fi
}

main "$@"
