{
  "dnsSearchDomains": null,
  "logConfiguration": {
    "logDriver": "awslogs",
    "secretOptions": null,
    "options": {
      "awslogs-group": "${log_group_name}",
      "awslogs-region": "us-east-1",
      "awslogs-stream-prefix": "ecs"
    }
  },
  "entryPoint": ${entry_point},
  "portMappings": ${port_mappings},
  "command": null,
  "linuxParameters": null,
  "cpu": ${cpu},
  "environment": ${environment},
  "resourceRequirements": null,
  "ulimits": null,
  "dnsServers": null,
  "mountPoints": null,
  "workingDirectory": null,
  "secrets": null,
  "dockerSecurityOptions": null,
  "memory": ${memory},
  "memoryReservation": ${memory_reservation},
  "volumesFrom": [],
  "stopTimeout": null,
  "image": "${image}",
  "startTimeout": null,
  "dependsOn": null,
  "disableNetworking": null,
  "interactive": null,
  "healthCheck": null,
  "essential": true,
  "links": null,
  "hostname": null,
  "extraHosts": null,
  "pseudoTerminal": null,
  "user": null,
  "readonlyRootFilesystem": null,
  "dockerLabels": null,
  "systemControls": null,
  "privileged": null,
  "name": "${name}"
}
