#!/usr/bin/env bash

# shellcheck disable=SC1090
source "${BASH_SOURCE[0]%/*}/../lib/bash/core.sh"

function main() {

  echo -e "${OK_COLOR}==> Pushing published changes from current branch to others..."

  GIT_REMOTE_URL="$(git config --get remote.origin.url)"
  if [[ "${GIT_REMOTE_URL}" != *"bitbucket.org/nabstudio/boilerplates.git" ]]; then
    echo "This script can only run in the boilerplate project." >&2
    return 1
  fi

  GIT_STATUS="$(git status --short --porcelain)"
  if [[ -n "${GIT_STATUS}" ]]; then
    echo "There are uncommitted changes. Please commit them before continue." >&2
    return 1
  fi

  GIT_BRANCH="$(git branch -vv | grep "\*" | awk '{print $2}')"
  GIT_UNPUSHED_COMMITS="$(git log "origin/${GIT_BRANCH}..HEAD")"
  echo "${GIT_UNPUSHED_COMMITS}"
  if [[ -n "${GIT_UNPUSHED_COMMITS}" ]]; then
    echo "There are unpushed commits. Please push them before continue." >&2
    return 1
  fi

}

main "$@" ||
  catch "$?" &&
  finally
