#!/usr/bin/env bash

# shellcheck disable=SC1090
source "${BASH_SOURCE[0]%/*}/../lib/bash/core.sh"

function main() {

  echo -e "${OK_COLOR}==> Pushing published changes from current branch to others..."

  if [[ -n "$(git status -s)" ]]; then
    echo "Please commit your changes." >&2
    return 1
  fi

}

main "$@" ||
  catch "$?" &&
  finally
